### ISSUE TITLE
[FEATURE REQUEST] filtering options

### ISSUE THREAD

**Issue by xinity** [mdjekic/pro4trello#1]
Hi ,

this extension in simply AWESOME !!!!
i've been wondering if there are somewhere on the roadmap , features like filtering ?
by complexity, tags .....

Keep up the awesome work !

**Comment by mdjekic** [comment]
Hi. The bad news is I'm currently heavily involved with a serious project. When the product launches I'll have time to resume work on Pro4Trello. The good news is I do intend to create more filters as I need them as well on my own projects - and the ones you mentioned are top of the list. 

Cheers.

**Comment by xinity** [comment]
hi @mdjekic ,

No worries, let me know, how it goes then

Cheers,

**Comment by pedall** [comment]
any change to this since april 2017? @mdjekic

**Comment by mdjekic** [comment]
Unfortunately I am not getting notifications from GitHub re: this repo. Have no clue as to why, all settings are there. Sucks I haven't even seen this question for 3 months. I'm sorry. I'm working slowly on getting something like this implemented, there was an update that prepares Pro4Trello for it.

**Comment by mdjekic** [comment]
Version 3.0 introduced all filters.
