### ISSUE TITLE
Conflict when using "Group" and "Card numbers" options

### ISSUE THREAD

**Issue by tazoony** [mdjekic/pro4trello#4]
Hello,

When I check both options **Recognize Groups** and **Display Card Numbers**, the card numbers are replaced by the card title, so the title is displayed twice : once in bold and in the color of the card number display (blue), and one more time in the normal style.

![capture_d ecran_070517_042317_pm](https://user-images.githubusercontent.com/7950353/27868831-418a7710-619e-11e7-85ae-24a0917befa5.jpg)

In the facts, here is what happens in less than 1 second :
1) Trello is loading
2) Card numbers are displayed in bold blue
3) Card numbers are replaced with the card title

Joffrey

**Comment by tazoony** [comment]
Sorry, in the facts, the problem occurs if I turn on "Display card numbers" and any other one option of the following :
- Recognize groups
- Recognize points
- Recognize custom tags
- Recognize priority

It seems that title string recognition generate this bug :( 

Joffrey

**Comment by mdjekic** [comment]
Did you try to simply refresh the page again?

**Comment by mdjekic** [comment]
I never managed to reproduce this exact bug. Are you using any other extensions that might influence Trello?

**Comment by tazoony** [comment]
Hello @mdjekic !
Thank you for replying. You was right, I've instaled "Plus for Trello". I've disabled this Chrome extension and now it works perfectly.

I've gonna have a look around "Plus for Trello" to know more about this bug.

Thank you !
